version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
          name: Download Dependencies
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Install Tree
          command: sudo apt-get install tree
      - run:
          name: Show tree
          command: tree
      - run:
          name: Upload apk
          command: curl -X POST --user "amitkhairnar44:SUkd24gGr4F5c8FFse4t" "https://api.bitbucket.org/2.0/repositories/amitkhairnar44/my-hub/downloads" --form files=@"/home/circleci/code/app/build/outputs/apk/debug/app_debug.apk"
      
      - store_artifacts:
          path: app/build/reports
          destination: reports
          path: app/build/outputs/apk/debug
          destination: apks
      - store_test_results:
          path: app/build/test-results